### ISSUE TITLE
how to build the dataset

### ISSUE THREAD

**Issue by ccsvd** [akashsengupta1997/SSP-3D#2]
hi,i want to build my own dataset like ssp-3d; i can get the init pose by vibe,
but i dont know how to train the fit model,
could you share the code,thanks.

**Comment by akashsengupta1997** [comment]
ssp3d_code_messy.zip
<https://drive.google.com/file/d/1GlPdAwcEaWzhWUbaML3AnQBhcP6IuhdS/view?usp=drive_web>

Hi,

Sorry for the late reply! Unfortunately the optimisation code is not
cleaned up for release, but I have attached a zip file that should contain
all the parts that you need (losses, NMR renderer for optimisation, and
some other stuff), hopefully it is not too much of a pain to put it
together for it to work. The python package dependencies are the same as
for the STRAPS repo. Note that NMR is actually an outdated differentiable
renderer now and I would recommend moving over to pytorch3d (
https://github.com/facebookresearch/pytorch3d).

Akash

**Comment by ccsvd** [comment]
thanks，but it need access authority get the file.

**Comment by akashsengupta1997** [comment]
oh whoops, does it work now?

**Comment by ccsvd** [comment]
no,can not open the link

**Comment by akashsengupta1997** [comment]
send me your email address and I will email it

**Comment by ccsvd** [comment]
it is ok,thanks!!!

**Comment by akashsengupta1997** [comment]
or try this: https://drive.google.com/file/d/1GlPdAwcEaWzhWUbaML3AnQBhcP6IuhdS/view?usp=sharing

**Comment by SajjadAemmi** [comment]
@akashsengupta1997 

what is `spin_results.pkl` and how i can generate this?

![image](https://user-images.githubusercontent.com/42681293/155288400-62d39dbf-7113-4b92-b7c6-b642fafd7cec.png)
